apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 231845408890.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 231845408890.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 7a3f2ce0
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
