apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 101678359701.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 101678359701.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: dfd91d9c
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
